### ISSUE TITLE
virtual shop product data missing when plugin update

### ISSUE THREAD

**Issue by ClancyNGC1277** [nulli0n/ExcellentShop-spigot#10]
I have the backup data , but I don't know how to restore it .

**Comment by ClancyNGC1277** [comment]
[19:24:36] [Server thread/ERROR]: [ExcellentShop] Could not load 'add84c4b-ea2a-4c5a-a540-245bbdc95b54' product in 'blocks' shop!
[19:24:36] [Server thread/WARN]: org.yaml.snakeyaml.error.YAMLException: Unable to find getter for property 'product' on object su.nightexpress.nexshop.shop.virtual.impl.product.VirtualProductStock@38c7f685:java.lang.reflect.InvocationTargetException
[19:24:36] [Server thread/WARN]: 	at org.yaml.snakeyaml.introspector.MethodProperty.get(MethodProperty.java:81)
[19:24:36] [Server thread/WARN]: 	at org.yaml.snakeyaml.representer.Representer.representJavaBean(Representer.java:107)
[19:24:36] [Server thread/WARN]: 	at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:83)
[19:24:36] [Server thread/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:122)
[19:24:36] [Server thread/WARN]: 	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:81)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.toNodeTree(YamlConfiguration.java:192)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.toNodeTree(YamlConfiguration.java:190)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.toNodeTree(YamlConfiguration.java:190)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:79)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65)
[19:24:36] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.api.config.JYML.save(JYML.java:107)
[19:24:36] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.api.config.JYML.saveChanges(JYML.java:117)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.shop.virtual.impl.product.VirtualProduct.read(VirtualProduct.java:92)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.shop.virtual.impl.shop.VirtualShop.lambda$loadProducts$9(VirtualShop.java:92)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:24:36] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.shop.virtual.impl.shop.VirtualShop.loadProducts(VirtualShop.java:99)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.shop.virtual.impl.shop.VirtualShop.load(VirtualShop.java:83)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.shop.virtual.VirtualShopModule.loadShops(VirtualShopModule.java:136)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.shop.virtual.VirtualShopModule.onLoad(VirtualShopModule.java:80)
[19:24:36] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:21)
[19:24:36] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.api.module.AbstractModule.setup(AbstractModule.java:29)
[19:24:36] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.api.module.AbstractModuleManager.register(AbstractModuleManager.java:55)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.module.ModuleManager.loadModules(ModuleManager.java:24)
[19:24:36] [Server thread/WARN]: 	at ExcellentShop-4.3.11.jar//su.nightexpress.nexshop.ExcellentShop.enable(ExcellentShop.java:58)
[19:24:36] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:224)
[19:24:36] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:95)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[19:24:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[19:24:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569)
[19:24:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480)
[19:24:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643)
[19:24:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442)
[19:24:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:344)
[19:24:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[19:24:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[19:24:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by nulli0n** [comment]
try redownload the latest version from SpigotMC, there was a silent update that should fix that.
