### ISSUE TITLE
Failed to get driver instance

### ISSUE THREAD

**Issue by tom4712** [nulli0n/ExcellentShop-spigot#11]
**There is no error when using NexEngine only, but there is an error when I run the server after adding ExcellenceShop.**
MC version is 1.19.4

[17:20:41] [Server thread/INFO]: Starting Metrics. Opt-out using the global bStats config.
[17:20:41] [Server thread/INFO]: [ExcellentShop] Enabling ExcellentShop v4.3.12
[17:20:41] [Server thread/INFO]: [ExcellentShop] Powered by: NexEngine
[17:20:41] [Server thread/INFO]: [ExcellentShop] Using 'en' language.
[17:20:41] [Server thread/INFO]: HikariPool-1 - Starting...
[17:20:41] [Server thread/WARN]: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:sqlite:/mcserver/plugins/ExcellentShop/data.db
[17:20:41] [Server thread/WARN]:        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
[17:20:41] [Server thread/WARN]:        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:326)
[17:20:41] [Server thread/WARN]:        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:112)
[17:20:41] [Server thread/WARN]:        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:93)
[17:20:41] [Server thread/WARN]:        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.api.data.connection.AbstractDataConnector.<init>(AbstractDataConnector.java:39)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.api.data.connection.AbstractDataConnector.<init>(AbstractDataConnector.java:20)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.api.data.connection.ConnectorSQLite.<init>(ConnectorSQLite.java:14)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.api.data.connection.ConnectorSQLite.<init>(ConnectorSQLite.java:10)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.api.data.AbstractDataHandler.<init>(AbstractDataHandler.java:52)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.api.data.AbstractUserDataHandler.<init>(AbstractUserDataHandler.java:35)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.api.data.AbstractUserDataHandler.<init>(AbstractUserDataHandler.java:31)
[17:20:41] [Server thread/WARN]:        at su.nightexpress.nexshop.data.ShopDataHandler.<init>(ShopDataHandler.java:57)
[17:20:41] [Server thread/WARN]:        at su.nightexpress.nexshop.data.ShopDataHandler.getInstance(ShopDataHandler.java:121)
[17:20:41] [Server thread/WARN]:        at su.nightexpress.nexshop.ExcellentShop.setupDataHandlers(ExcellentShop.java:87)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:216)
[17:20:41] [Server thread/WARN]:        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:95)
[17:20:41] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[17:20:41] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[17:20:41] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[17:20:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:536)
[17:20:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:450)
[17:20:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[17:20:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[17:20:41] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[17:20:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[17:20:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[17:20:41] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:20:41] [Server thread/WARN]: Caused by: java.sql.SQLException: No suitable driver
[17:20:41] [Server thread/WARN]:        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:299)
[17:20:41] [Server thread/WARN]:        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
[17:20:41] [Server thread/WARN]:        ... 27 more
[17:20:41] [Server thread/ERROR]: [ExcellentShop] Could not setup plugin Data Handler!

**Comment by nulli0n** [comment]
Update both plugins.
