### ISSUE TITLE
bug on shift left click

### ISSUE THREAD

**Issue by Tmdoofking** [nulli0n/ExcellentShop-spigot#18]
shift left click will happen this (1.19.4)
![image](https://github.com/nulli0n/ExcellentShop-spigot/assets/70594985/defbecf2-6e35-4f10-8b43-57232c8841a4)

[14:12:30 ERROR]: Could not pass event InventoryClickEvent to NexEngine v2.2.11
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at java.lang.String.join(String.java:3320) ~[?:?]
        at su.nightexpress.nexshop.shop.virtual.impl.product.VirtualProduct.lambda$new$0(VirtualProduct.java:40) ~[ExcellentShop-4.5.4.jar:?]
        at su.nexmedia.engine.utils.StringUtil.replaceEach(StringUtil.java:111) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.placeholder.PlaceholderMap.lambda$replacer$1(PlaceholderMap.java:57) ~[NexEngine.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.replace(ItemUtil.java:129) ~[NexEngine.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.lambda$replace$2(ItemUtil.java:117) ~[NexEngine.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.mapMeta(ItemUtil.java:57) ~[NexEngine.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.replace(ItemUtil.java:117) ~[NexEngine.jar:?]
        at su.nightexpress.nexshop.shop.virtual.editor.menu.ProductMainEditor.lambda$new$14(ProductMainEditor.java:156) ~[ExcellentShop-4.5.4.jar:?]
        at su.nexmedia.engine.api.menu.item.ItemOptions.modifyDisplay(ItemOptions.java:56) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.menu.impl.Menu.lambda$open$6(Menu.java:111) ~[NexEngine.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at su.nexmedia.engine.api.menu.impl.Menu.open(Menu.java:109) ~[NexEngine.jar:?]
        at su.nightexpress.nexshop.shop.virtual.editor.menu.ProductListEditor.lambda$onPrepare$2(ProductListEditor.java:130) ~[ExcellentShop-4.5.4.jar:?]
        at su.nexmedia.engine.api.menu.impl.Menu.onClick(Menu.java:160) ~[NexEngine.jar:?]
        at su.nightexpress.nexshop.shop.virtual.editor.menu.ProductListEditor.onClick(ProductListEditor.java:224) ~[ExcellentShop-4.5.4.jar:?]
        at su.nexmedia.engine.api.menu.impl.MenuListener.onMenuItemClick(MenuListener.java:70) ~[NexEngine.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor11.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3196) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nulli0n** [comment]
Fixed in v4.6.0
