### ISSUE TITLE
Issue Excellentshop with coinsengine or nexengine?

### ISSUE THREAD

**Issue by OyenDeveloper** [nulli0n/ExcellentShop-spigot#26]
I previously bought excellentshop. After installing it, I found an error with the excellentshop plugin.
`[14:50:14 ERROR]: Error occurred while enabling ExcellentShop v4.8.4 (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    su/nightexpress/nexshop/currency/impl/CoinsEngineCurrency.lambda$give$1(DLsu/nightexpress/coinsengine/data/impl/CoinsUser;)V @21: invokevirtual
  Reason:
    Type 'su/nightexpress/coinsengine/data/impl/CoinsUser' (current frame, stack[1]) is not assignable to 'su/nexmedia/engine/api/data/AbstractUser'
  Current Frame:
    bci: @21
    flags: { }
    locals: { 'su/nightexpress/nexshop/currency/impl/CoinsEngineCurrency', double, double_2nd, 'su/nightexpress/coinsengine/data/impl/CoinsUser' }
    stack: { 'su/nightexpress/coinsengine/data/UserManager', 'su/nightexpress/coinsengine/data/impl/CoinsUser' }
  Bytecode:
    0000000: 2dc7 0004 b12d 2ab4 001a b600 7a27 b600
    0000010: b2b8 00aa 2db6 00b0 b1                 
  Stackmap Table:
    same_frame(@5)
        at su.nightexpress.nexshop.currency.CurrencyManager.onLoad(CurrencyManager.java:58) ~[ExcellentShop-4.8.4.jar:?]
        at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:25) ~[NexEngine.jar:?]
        at su.nightexpress.nexshop.ExcellentShop.enable(ExcellentShop.java:63) ~[ExcellentShop-4.8.4.jar:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:219) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.jar:git-Purpur-1990]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.jar:git-Purpur-1990]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.20.jar:git-Purpur-1990]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.jar:git-Purpur-1990]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

ExcellentShop version: 4.8.4
CoinsEngine version: 2.2.0
NexEngine versiion: 2.2.12

FYI: I didn't make CoinEngine the main economy, because the Towny plugin doesn't support CoinEngine.

**Comment by nulli0n** [comment]
Update Excellentshop
