### ISSUE TITLE
"this.moduleCommand" is null

### ISSUE THREAD

**Issue by Mfweb** [nulli0n/ExcellentShop-spigot#4]
game verison:
`git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)`
java verison:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment 21.3 (build 16.0.1+9)
OpenJDK 64-Bit Server VM 21.3 (build 16.0.1+9, mixed mode, sharing)
```
log:
```
[18:00:03 INFO]: [ExcellentShop] Enabling ExcellentShop v4.0.7.1
[18:00:03 INFO]: [ExcellentShop] Powered by: NexEngine
[18:00:03 INFO]: [ExcellentShop] Found 0 external module(s).
[18:00:03 INFO]: [ExcellentShop] Registered currency: vault
[18:00:03 ERROR]: Error occurred while enabling ExcellentShop v4.0.7.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "su.nightexpress.nexshop.modules.command.ShopModuleCommand.addDefaultCommand(su.nexmedia.engine.api.command.AbstractCommand)" because "this.moduleCommand" is null
        at su.nightexpress.nexshop.shop.virtual.VirtualShop.onLoad(VirtualShop.java:87) ~[ExcellentShop-4.0.7.1.jar:?]
        at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:21) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.module.AbstractModule.setup(AbstractModule.java:33) ~[NexEngine.jar:?]
        at su.nexmedia.engine.module.ModuleManager.register(ModuleManager.java:70) ~[NexEngine.jar:?]
        at su.nightexpress.nexshop.modules.ModuleCache.setup(ModuleCache.java:24) ~[ExcellentShop-4.0.7.1.jar:?]
        at su.nightexpress.nexshop.ExcellentShop.enable(ExcellentShop.java:54) ~[ExcellentShop-4.0.7.1.jar:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:215) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:84) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-353]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[18:00:03 INFO]: [ExcellentShop] Disabling ExcellentShop v4.0.7.1
[18:00:03 INFO]: [ExcellentShop] [Citizens Hook] Unregistered listeners
[18:00:03 INFO]: [ExcellentShop] Auto-save: Saved 0 online users | 0 offline users.
```

**Comment by Mfweb** [comment]
> Should be fixed in the latest version. Make sure to update Engine plugin too.

4.0.7.2a: not fixed yet

**Comment by Mfweb** [comment]
> 4.0.7.2a: not fixed yet

4.0.7.3: not fixed yet

**Comment by nulli0n** [comment]
In each module 'settings.yml' change 'command-aliases' to 'Command_Aliases'.
