### ISSUE TITLE
Issue with VotingPlugin

### ISSUE THREAD

**Issue by nightmvre** [nulli0n/ExcellentShop-spigot#40]
[17:57:11 ERROR]: Could not pass event PlayerJoinEvent to ExcellentShop v4.11.5
java.lang.IllegalStateException: PlayerReceivePointsEvent may only be triggered asynchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at VotingPlugin.jar/com.bencodez.votingplugin.user.VotingPluginUser.addPoints(VotingPluginUser.java:132) ~[VotingPlugin.jar:?]
        at VotingPlugin.jar/com.bencodez.votingplugin.user.VotingPluginUser.addPoints(VotingPluginUser.java:127) ~[VotingPlugin.jar:?]
        at ExcellentShop-4.11.5.jar/su.nightexpress.nexshop.currency.handler.VotingPluginHandler.give(VotingPluginHandler.java:33) ~[ExcellentShop-4.11.5.jar:?]
        at ExcellentShop-4.11.5.jar/su.nightexpress.nexshop.shop.chest.listener.ShopListener.lambda$onPlayerJoin$0(ShopListener.java:54) ~[ExcellentShop-4.11.5.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at ExcellentShop-4.11.5.jar/su.nightexpress.nexshop.shop.chest.listener.ShopListener.onPlayerJoin(ShopListener.java:53) ~[ExcellentShop-4.11.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1153.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:57:11 INFO]: .KINGSLOTH9156[/110.32.141.53:37096] logged in with entity id 13782 at ([world]14962.639, 88.5625, 10490.145)

**Comment by nulli0n** [comment]
Fixed in v4.11.6
