### ISSUE TITLE
It is already the latest version, why is there an error?

### ISSUE THREAD

**Issue by xiaofengv233** [nulli0n/ExcellentShop-spigot#9]
[11:22:29 INFO]: ZiXu issued server command: /excellentshop:shop
[11:22:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'excellentshop:shop' in su.nexmedia.engine.command.CommandRegister(virtualshop)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2373) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2333) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1952]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "su.nightexpress.nexshop.currency.CurrencyManager.getCurrencies()" because the return value of "su.nightexpress.nexshop.ExcellentShop.getCurrencyManager()" is null
        at su.nightexpress.nexshop.shop.virtual.impl.shop.VirtualShop.lambda$replacePlaceholders$2(VirtualShop.java:96) ~[[E][商店]ExcellentShop-4.3.8.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.replace(ItemUtil.java:98) ~[[N][前置]NexEngine.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.lambda$replace$2(ItemUtil.java:93) ~[[N][前置]NexEngine.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.mapMeta(ItemUtil.java:41) ~[[N][前置]NexEngine.jar:?]
        at su.nexmedia.engine.utils.ItemUtil.replace(ItemUtil.java:93) ~[[N][前置]NexEngine.jar:?]
        at su.nightexpress.nexshop.shop.virtual.menu.ShopMainMenu.lambda$onPrepare$3(ShopMainMenu.java:67) ~[[E][商店]ExcellentShop-4.3.8.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at su.nightexpress.nexshop.shop.virtual.menu.ShopMainMenu.onPrepare(ShopMainMenu.java:52) ~[[E][商店]ExcellentShop-4.3.8.jar:?]
        at su.nexmedia.engine.api.menu.AbstractMenu.open(AbstractMenu.java:132) ~[[N][前置]NexEngine.jar:?]
        at su.nightexpress.nexshop.shop.virtual.VirtualShopModule.openMainMenu(VirtualShopModule.java:221) ~[[E][商店]ExcellentShop-4.3.8.jar:?]
        at su.nightexpress.nexshop.shop.virtual.command.OpenCommand.onExecute(OpenCommand.java:59) ~[[E][商店]ExcellentShop-4.3.8.jar:?]
        at su.nexmedia.engine.api.command.AbstractCommand.execute(AbstractCommand.java:170) ~[[N][前置]NexEngine.jar:?]
        at su.nexmedia.engine.api.command.GeneralCommand.onCommand(GeneralCommand.java:86) ~[[N][前置]NexEngine.jar:?]
        at su.nexmedia.engine.command.CommandRegister.execute(CommandRegister.java:96) ~[[N][前置]NexEngine.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]

**Comment by nulli0n** [comment]
Update NexEngine
